In [1]:
import pandas as pd
import numpy as np
from collections import Counter

In [2]:
file_path = r"C:\Users\Braydon\Desktop\Shein_Data\Pivot_Data\Aday\Aday_Cleaned.csv"

In [3]:
df = pd.read_csv(file_path)

In [13]:
df

                      Cloth_Desc  Price
0    All Day Long Sleeve T-Shirt   75.0
1    All Day Long Sleeve T-Shirt   75.0
2    All Day Long Sleeve T-Shirt   75.0
3           All Weather Cardigan  200.0
4           All Weather Cardigan  200.0
..                           ...    ...
254                Warm Up Pants  190.0
255         Wind Down Wrap Dress  300.0
256         Wind Down Wrap Dress  300.0
257          Wrapped In Flax Top  150.0
258          Wrapped In Flax Top  150.0

[259 rows x 2 columns]

In [5]:
cloth_word_lst = []

for item in df['Cloth_Desc']:
    item = item.split()
    for thing in item:
        cloth_word_lst.append(thing)

In [14]:
cloth_word_count = Counter(cloth_word_lst)

In [15]:
cloth_word_count

Counter({'All': 8,
         'Day': 4,
         'Long': 4,
         'Sleeve': 3,
         'T-Shirt': 23,
         'Weather': 3,
         'Cardigan': 3,
         'Back': 4,
         'To': 8,
         'Front': 2,
         'Shirt': 17,
         'Dress': 27,
         'Bend': 2,
         'and': 2,
         'Stretch': 6,
         'Pants': 43,
         'Best': 1,
         'In': 8,
         'Class': 1,
         'Bodysuit': 1,
         'Bio': 1,
         'Detergent': 1,
         '-': 3,
         'Free': 3,
         '&': 1,
         'Clear': 1,
         'Brakes': 1,
         'On': 2,
         'Leggings': 15,
         'Chill': 6,
         'Out': 3,
         'Blouse': 4,
         'City': 2,
         'Summits': 2,
         'Vest': 2,
         'Comfort': 4,
         'Zone': 4,
         'Hoodie': 4,
         'Comfy': 2,
         'Days': 10,
         'Cool-Down': 2,
         'Crop': 7,
         'Top': 34,
         'Cozy': 7,
         'Cool': 8,
         'Up': 31,
         'And': 7,
         'Roll': 5,
         'It': 40,
         'Culotte': 1,
         'Shorts': 13,
         'Cropped': 1,
         'Suits': 2,
         'You': 2,
         'Dawn': 1,
         'Dusk': 1,
         'Kimono': 1,
         'to': 1,
         'Night': 1,
         'Destination': 4,
         'Jumpsuit': 5,
         'Dial': 1,
         'Down': 8,
         'Double': 4,
         'Take': 1,
         'Breasted': 1,
         'Blazer': 6,
         'Socks': 2,
         'Dream': 7,
         'Harder': 3,
         'Racerback': 3,
         'Tank': 14,
         'Ease': 2,
         'Paperbag': 2,
         'Easy': 7,
         'Essentialist': 10,
         '(3-pack)': 3,
         'Everyday': 3,
         'Float': 2,
         'Linen': 9,
         'Fresh': 1,
         'Start': 1,
         'Got': 1,
         'Covered': 1,
         'Suit': 1,
         'Hail': 2,
         'Yes': 2,
         'Joggers': 8,
         'Here.': 1,
         'Now.': 1,
         'Silk': 1,
         'Bandana': 1,
         'Hit': 2,
         'Snooze': 2,
         'Travel': 2,
         'Eye': 2,
         'Mask': 2,
         'Home': 4,
         'Pullover': 17,
         "I'm": 4,
         'Flaxible': 2,
         'Ice': 3,
         'Pop': 3,
         'Inside': 1,
         'Reversible': 1,
         'Jacket': 3,
         "It's": 4,
         'A': 27,
         'Classic': 1,
         'a': 1,
         'Swirl': 3,
         'Wrap': 17,
         'Skirt': 3,
         'Keep': 3,
         'Arm': 3,
         'Warmers': 3,
         'Kick': 2,
         'Layered': 4,
         'Thermal': 4,
         'LBD': 4,
         'Legacy': 1,
         'Trench': 1,
         'Let': 1,
         'Loose': 1,
         'Lighten': 3,
         'Sports': 3,
         'Bra': 3,
         'Lighter': 1,
         'Like': 18,
         'Boss': 11,
         'Fleece': 1,
         'Sweatshirt': 3,
         'Hug': 2,
         'Haul': 1,
         'Satin': 2,
         'Made': 6,
         'Necessi-T-Shirt': 7,
         'No': 3,
         'Sweat': 3,
         'Sweater': 3,
         'Not': 2,
         'So': 2,
         'Basic': 2,
         'Offset': 1,
         'Your': 1,
         'Next': 1,
         'Trip': 1,
         'Board': 1,
         'Over': 1,
         'One': 1,
         'Overhead': 1,
         'Turtleneck': 1,
         'Pack': 2,
         'Pleat': 2,
         'Repeat': 2,
         'Portfolio': 5,
         'Tailored': 7,
         'Rain': 3,
         'Or': 3,
         'Shine': 3,
         'Hooded': 3,
         'Scarf': 6,
         'Relax': 2,
         'Flax': 4,
         'Self-Care': 1,
         'Shrug': 3,
         'Off': 3,
         'Simple': 1,
         'Things': 1,
         'Snap': 5,
         'Something': 24,
         'Borrowed': 15,
         'Button': 5,
         'Straight': 4,
         'Strategy': 3,
         'Sunday': 1,
         'Morning': 1,
         'Tailor-Made': 2,
         "That's": 6,
         'Three-In-One': 4,
         'Hat': 4,
         'Throw': 7,
         'Higher': 5,
         'Notch': 1,
         'Scoop': 1,
         'Neck': 1,
         'Trailblazer': 2,
         'Belted': 2,
         'Latte': 1,
         'Oat': 1,
         'Turn': 12,
         'Around': 3,
         'Twist': 4,
         '+': 4,
         'Under': 1,
         'Wraps': 1,
         'The': 2,
         'Air': 2,
         'Warm': 4,
         'Year': 2,
         'Wind': 2,
         'Wrapped': 2})

In [16]:
data = cloth_word_count.most_common()

In [17]:
data

[('Pants', 43),
 ('It', 40),
 ('Top', 34),
 ('Up', 31),
 ('Dress', 27),
 ('A', 27),
 ('Something', 24),
 ('T-Shirt', 23),
 ('Like', 18),
 ('Shirt', 17),
 ('Pullover', 17),
 ('Wrap', 17),
 ('Leggings', 15),
 ('Borrowed', 15),
 ('Tank', 14),
 ('Shorts', 13),
 ('Turn', 12),
 ('Boss', 11),
 ('Days', 10),
 ('Essentialist', 10),
 ('Linen', 9),
 ('All', 8),
 ('To', 8),
 ('In', 8),
 ('Cool', 8),
 ('Down', 8),
 ('Joggers', 8),
 ('Crop', 7),
 ('Cozy', 7),
 ('And', 7),
 ('Dream', 7),
 ('Easy', 7),
 ('Necessi-T-Shirt', 7),
 ('Tailored', 7),
 ('Throw', 7),
 ('Stretch', 6),
 ('Chill', 6),
 ('Blazer', 6),
 ('Made', 6),
 ('Scarf', 6),
 ("That's", 6),
 ('Roll', 5),
 ('Jumpsuit', 5),
 ('Portfolio', 5),
 ('Snap', 5),
 ('Button', 5),
 ('Higher', 5),
 ('Day', 4),
 ('Long', 4),
 ('Back', 4),
 ('Blouse', 4),
 ('Comfort', 4),
 ('Zone', 4),
 ('Hoodie', 4),
 ('Destination', 4),
 ('Double', 4),
 ('Home', 4),
 ("I'm", 4),
 ("It's", 4),
 ('Layered', 4),
 ('Thermal', 4),
 ('LBD', 4),
 ('Flax', 4),
 ('Straight', 4),
 ('Three-In-One', 4),
 ('Hat', 4),
 ('Twist', 4),
 ('+', 4),
 ('Warm', 4),
 ('Sleeve', 3),
 ('Weather', 3),
 ('Cardigan', 3),
 ('-', 3),
 ('Free', 3),
 ('Out', 3),
 ('Harder', 3),
 ('Racerback', 3),
 ('(3-pack)', 3),
 ('Everyday', 3),
 ('Ice', 3),
 ('Pop', 3),
 ('Jacket', 3),
 ('Swirl', 3),
 ('Skirt', 3),
 ('Keep', 3),
 ('Arm', 3),
 ('Warmers', 3),
 ('Lighten', 3),
 ('Sports', 3),
 ('Bra', 3),
 ('Sweatshirt', 3),
 ('No', 3),
 ('Sweat', 3),
 ('Sweater', 3),
 ('Rain', 3),
 ('Or', 3),
 ('Shine', 3),
 ('Hooded', 3),
 ('Shrug', 3),
 ('Off', 3),
 ('Strategy', 3),
 ('Around', 3),
 ('Front', 2),
 ('Bend', 2),
 ('and', 2),
 ('On', 2),
 ('City', 2),
 ('Summits', 2),
 ('Vest', 2),
 ('Comfy', 2),
 ('Cool-Down', 2),
 ('Suits', 2),
 ('You', 2),
 ('Socks', 2),
 ('Ease', 2),
 ('Paperbag', 2),
 ('Float', 2),
 ('Hail', 2),
 ('Yes', 2),
 ('Hit', 2),
 ('Snooze', 2),
 ('Travel', 2),
 ('Eye', 2),
 ('Mask', 2),
 ('Flaxible', 2),
 ('Kick', 2),
 ('Hug', 2),
 ('Satin', 2),
 ('Not', 2),
 ('So', 2),
 ('Basic', 2),
 ('Pack', 2),
 ('Pleat', 2),
 ('Repeat', 2),
 ('Relax', 2),
 ('Tailor-Made', 2),
 ('Trailblazer', 2),
 ('Belted', 2),
 ('The', 2),
 ('Air', 2),
 ('Year', 2),
 ('Wind', 2),
 ('Wrapped', 2),
 ('Best', 1),
 ('Class', 1),
 ('Bodysuit', 1),
 ('Bio', 1),
 ('Detergent', 1),
 ('&', 1),
 ('Clear', 1),
 ('Brakes', 1),
 ('Culotte', 1),
 ('Cropped', 1),
 ('Dawn', 1),
 ('Dusk', 1),
 ('Kimono', 1),
 ('to', 1),
 ('Night', 1),
 ('Dial', 1),
 ('Take', 1),
 ('Breasted', 1),
 ('Fresh', 1),
 ('Start', 1),
 ('Got', 1),
 ('Covered', 1),
 ('Suit', 1),
 ('Here.', 1),
 ('Now.', 1),
 ('Silk', 1),
 ('Bandana', 1),
 ('Inside', 1),
 ('Reversible', 1),
 ('Classic', 1),
 ('a', 1),
 ('Legacy', 1),
 ('Trench', 1),
 ('Let', 1),
 ('Loose', 1),
 ('Lighter', 1),
 ('Fleece', 1),
 ('Haul', 1),
 ('Offset', 1),
 ('Your', 1),
 ('Next', 1),
 ('Trip', 1),
 ('Board', 1),
 ('Over', 1),
 ('One', 1),
 ('Overhead', 1),
 ('Turtleneck', 1),
 ('Self-Care', 1),
 ('Simple', 1),
 ('Things', 1),
 ('Sunday', 1),
 ('Morning', 1),
 ('Notch', 1),
 ('Scoop', 1),
 ('Neck', 1),
 ('Latte', 1),
 ('Oat', 1),
 ('Under', 1),
 ('Wraps', 1)]

In [19]:
keyword_df = pd.DataFrame(data, columns = ["Keyword","Frequency"])

In [20]:
keyword_df

    Keyword  Frequency
0     Pants         43
1        It         40
2       Top         34
3        Up         31
4     Dress         27
..      ...        ...
197    Neck          1
198   Latte          1
199     Oat          1
200   Under          1
201   Wraps          1

[202 rows x 2 columns]

In [21]:
keyword_df.to_csv("Aday_keywords.csv",index = False)